[build]
target-applies-to-host = false

[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-musl-gcc"
# Garante linkagem estática total — binário self-contained como /init
rustflags = [
    "-C", "target-feature=+crt-static",
    "-C", "link-arg=-static",
    # Otimizações para Cortex-A53 (MSM8916)
    "-C", "target-cpu=cortex-a53",
]

[target.x86_64-unknown-linux-gnu]
linker = "rust-lld"
rustflags = [
    "-C", "link-arg=-L/home/huneyoliv/Projetos/SGP-Ciclobike/.libs",
    "--cfg", "libc",
    "--cfg", "linux_kernel",
    "--cfg", "linux_like",
]

[target.x86_64-unknown-linux-musl]
linker = "rust-lld"
rustflags = [
    "-C", "link-arg=-L/home/huneyoliv/Projetos/SGP-Ciclobike/.libs",
    "-C", "target-feature=+crt-static",
    "-C", "link-arg=-static",
    "--cfg", "libc",
    "--cfg", "linux_kernel",
    "--cfg", "linux_like",
]

[host]
linker = "rust-lld"
rustflags = [
    "-C", "link-arg=-L/home/huneyoliv/Projetos/SGP-Ciclobike/.libs",
    "--cfg", "libc",
    "--cfg", "linux_kernel",
    "--cfg", "linux_like",
]
